'use client';

import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { legalApi } from '@/lib/api/client';
import { useCaseStore } from '@/lib/store/case.store';
import { 
  PageHeader, IntelCard, IntelCardHeader, IntelCardTitle, IntelCardContent, 
  EmptyState 
} from '@/components/ui';
import { Button } from '@/components/ui/button';
import { Terminal, RefreshCw } from 'lucide-react';

export default function ReasoningPage() {
  const { activeCaseId } = useCaseStore();

  const { data: traces = [], isLoading, refetch, isRefetching } = useQuery({
    queryKey: ['reasoning-traces', activeCaseId],
    queryFn: () => legalApi.getReasoningTraces(activeCaseId!),
    enabled: !!activeCaseId,
  });

  if (!activeCaseId) {
    return (
      <EmptyState 
        title="No active case workspace" 
        description="Please select an active case from the top header or cases explorer to view the logic reasoning traces."
      />
    );
  }

  return (
    <div className="space-y-6">
      <PageHeader 
        title="Cognitive Reasoning Traces" 
        description="Inspect low-level execution logs generated by ORACLE, AIRE, and Deception inference engines."
        actions={
          <Button 
            variant="secondary"
            onClick={() => refetch()}
            disabled={isLoading || isRefetching}
            className="font-mono text-xs border-border-subtle"
          >
            <RefreshCw className={isRefetching ? "w-3.5 h-3.5 animate-spin" : "w-3.5 h-3.5"} />
          </Button>
        }
      />

      <div className="space-y-4">
        {isLoading ? (
          <div className="space-y-2">
            {[1, 2].map((_, i) => (
              <div key={i} className="h-20 bg-surface rounded animate-pulse" />
            ))}
          </div>
        ) : traces.length === 0 ? (
          <EmptyState 
            title="No reasoning traces found" 
            description="Reasoning logs are empty. Logic updates trigger traces during evidence ingestion or manual scans."
            icon={Terminal}
          />
        ) : (
          traces.map((t) => (
            <IntelCard key={t.id}>
              <IntelCardHeader className="py-4">
                <div className="flex justify-between items-start">
                  <div className="flex items-center gap-2">
                    <Terminal className="w-4 h-4 text-intel-blue" />
                    <span className="text-xs font-mono font-bold text-text-primary">
                      Source: {t.engine_source}
                    </span>
                  </div>
                  <span className="text-[10px] font-mono text-text-muted">
                    {new Date(t.timestamp).toLocaleString()}
                  </span>
                </div>
              </IntelCardHeader>
              <IntelCardContent className="space-y-3">
                <div className="bg-base/50 p-3.5 rounded border border-border-subtle font-mono text-xs text-text-secondary select-all">
                  Event context: {t.input_event_type}
                </div>
                <div className="space-y-1">
                  <span className="text-[9px] font-mono font-bold text-text-secondary uppercase">Steps completed</span>
                  <div className="flex flex-wrap gap-1">
                    {t.steps_completed?.map((step: string, sIdx: number) => (
                      <span key={sIdx} className="px-2 py-0.5 rounded text-[9px] font-mono font-bold border border-border bg-elevated text-text-secondary">
                        {step}
                      </span>
                    ))}
                  </div>
                </div>
                <div className="space-y-1">
                  <span className="text-[9px] font-mono font-bold text-text-secondary uppercase">Reasoning output payload</span>
                  <pre className="bg-base/20 border border-border-subtle p-3 rounded-lg font-mono text-[10px] text-intel-cyan overflow-x-auto max-h-40">
                    {t.reasoning_output}
                  </pre>
                </div>
              </IntelCardContent>
            </IntelCard>
          ))
        )}
      </div>
    </div>
  );
}
